### ISSUE TITLE
Add possibility to decode via mmal in BGRA

### ISSUE THREAD

**Issue by LongChair** [raspberrypi/userland#250] opened 2015-07-26 10:32 UTC
I have been using the mmal decoder with the provided samples and using qt5.

In some parts of qt5 (ie webengine), chromium requires to use BGRA imagedata which are not available with the decoder.

As the encoding value is defined in https://github.com/raspberrypi/userland/blob/b834074d0c0d9d7e64c133ab14ed691999cee990/interface/mmal/mmal_encodings.h#L79 , i was wondering if that was possible to have the decoder output BGRA rather than the default RGBA data. 

I tried this but it results in an invalid format error when setting up the decoder.

I'm therefore not sure if this is a HW limitation or just the fact that it's not been implemented yet ?

**Comment by popcornmix** [comment] 2015-07-27 14:50
Duplicate of https://github.com/raspberrypi/firmware/issues/452

**Closed by popcornmix** 2015-07-27 14:50 UTC
