### ISSUE TITLE
raspivid --help output is printed to stderr instead of stdout

### ISSUE THREAD

**Issue by derekenos** [raspberrypi/userland#244] opened 2015-05-31 18:48 UTC
This prevents pagers like `less` and `more` from working as expected when the height of the content exceeds that of the terminal window.

Example:

`raspivid --help | less` displays only the last page of content:
![screenshot - 05312015 - 02 38 14 pm](https://cloud.githubusercontent.com/assets/585182/7903203/f1628e82-07a2-11e5-92a6-81368852eb69.png)

Redirecting `stderr` to `stdout` allows `less` to work as expected, `raspivid --help 2>&1 | less`:
![screenshot - 05312015 - 02 43 45 pm](https://cloud.githubusercontent.com/assets/585182/7903234/7628e38c-07a3-11e5-992b-f2fe6659554b.png)

**Comment by 6by9** [comment] 2015-06-01 23:03
Feel free to sort out a patch and make a pull request.
You are right that all the fprintf lines are set to stderr, when stdout would probably be more useful.

Likewise I believe all the vcos_log_xxx lines are going to stderr. A quick tweak to https://github.com/raspberrypi/userland/blob/master/interface/vcos/pthreads/vcos_pthreads.c#L334 is likely to fix that, although that affects all users of vcos logging on the ARM, which includes the MMAL IPC framework and the likes.

**Comment by popcornmix** [comment] 2015-06-02 00:01
Be aware that raspivid supports output of encoded data to stdout and so you need to be careful not to mix logging output with that.

**Comment by JamesH65** [comment] 2015-06-02 07:43
Following on from popcornmix, all output was pushed to stderr in order to
enable the encoded output to stdout. However, I see no reason off hand why
the help cannot go to stdout, since you won't be using them at the same
time as encoded output.

**Comment by 6by9** [comment] 2016-01-01 18:30
Change merged that sends the help text to stdout instead of stderr.
Please retest and close, unless you think there is something further to do.

**Comment by 6by9** [comment] 2016-01-16 20:10
@popcornmix Do you want to close this? The issue is fixed, and the original poster seems to have gone away.

**Closed** 2016-01-16 20:15 UTC

**Comment by derekenos** [comment] 2016-01-16 20:30
Sorry, I've been meaning to respond. Thanks for the fix!
