### ISSUE TITLE
raspivid sketch not applied when saving

### ISSUE THREAD

**Issue by DuncanRowland** [raspberrypi/userland#94] opened 2013-10-03 16:01 UTC
raspivid -ifx sketch
works fine
raspivid -ifx sketch -o x
does not show the sketch filter as being applied.

**Comment by Ruffio** [comment] 2015-06-26 21:43
@DuncanRowland is this still an issue?

**Comment by DrRowland** [comment] 2015-06-29 07:55
Not sure it it's a issue, the save file still does not have the filter applied, but perhaps this is by design.

**Comment by 6by9** [comment] 2015-06-29 12:33
Not entirely by design, but very unlikely to get fixed. 

When video encoding, the GPU uses a different image format to stills or preview without encoding, and there are a couple of effect plugins that don't support that format.
I did look into this under https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=83353&hilit=address+effects&start=25#p590941 Emboss and blur got converted, but not the others.
Mainly it's the effects that need context from adjoining pixels that are tricky with this image format, and sketch requires context.

**Comment by JamesH65** [comment] 2017-12-05 11:33
Closing as a Wont Fix.

**Closed by JamesH65** 2017-12-05 11:33 UTC
