### ISSUE TITLE
v3d fec00000.v3d : MMU error from client L2T (0) at 0x3xxxxxx, pte invalid

### ISSUE THREAD

**Issue by Ash-S** [raspberrypi/userland#698] opened 2021-07-06 06:11 UTC

**Comment by 6by9** [comment] 2021-07-06 07:21
Looks to be an unintended duplicate of #699

**Closed by 6by9** 2021-07-06 07:21 UTC

**Comment by Ash-S** [comment] 2021-07-06 07:26
@6by9 ; sorry, it's by mistake. how can I remove this thread?

**Comment by 6by9** [comment] 2021-07-06 09:46
> sorry, it's by mistake. how can I remove this thread?

You can't, but I have closed it to denote that no further action will be taken on it.
