### ISSUE TITLE
Regression: MMAL_BUFFER_HEADER_FLAG_FRAME_END not set

### ISSUE THREAD

**Issue by aizvorski** [raspberrypi/userland#174] opened 2014-05-17 07:20 UTC
At the end of frame, in encoder_buffer_callback(), buffer->flags used to have MMAL_BUFFER_HEADER_FLAG_FRAME_END bit set (which allows doing something at end of frame in a patched raspivid). 

As of eccb81050afd177da1923404b366c6226f29bfe0, that is set as appropriate.
As of 677f3cc646c8847822998c6409a748c900897076, that is never set.

Does requesting inline motion vectors somehow break end of frame?  Does this affect other things which rely on end of frame?

**Comment by Ruffio** [comment] 2015-06-27 18:24
@aizvorski is this still an issue?

**Comment by 6by9** [comment] 2017-10-10 14:24
Not seeing this.
Header bytes have 0x24 (```MMAL_BUFFER_HEADER_FLAG_CONFIG | MMAL_BUFFER_HEADER_FLAG_FRAME_END```
Normal encoded data has 0x04 (```MMAL_BUFFER_HEADER_FLAG_FRAME_END```)
Motion vectors have 0x84 (```MMAL_BUFFER_HEADER_FLAG_CODECSIDEINFO | MMAL_BUFFER_HEADER_FLAG_FRAME_END```).
That's as expected.

Closing due to being unable to reproduce, and no further response from the reporter.

**Closed by 6by9** 2017-10-10 14:24 UTC

**Comment by KahnSoft** [comment] 2022-09-04 13:00
i have an nearly problem, my encoder_buffer_callback  will called only once, and then never again.
will only capture theframe not need to open a view.

my first test has out commenting open the view, have connected with encoder, but got only one single call to callback- of encoder.


eaXAMPLE:
`
#include "stdio.h"
#include <stdlib.h>

#include "interface/mmal/mmal.h"
//#include "interface/mmal/mmal_logging.h"
#include "interface/mmal/mmal_buffer.h"
#include "interface/mmal/util/mmal_util.h"
#include "interface/mmal/util/mmal_util_params.h"
#include "interface/mmal/util/mmal_default_components.h"
#include "interface/mmal/util/mmal_connection.h"


#include <semaphore.h>

#define CAMWIDTH  1980
#define CAMHEIGHT 1080
int cnt=0;

MMAL_COMPONENT_T     *preview = 0;
MMAL_STATUS_T         status;
MMAL_COMPONENT_T     *camera  = 0;
MMAL_COMPONENT_T     *encoder = 0;
MMAL_POOL_T *pool;

VCOS_STATUS_T vcos_status;
VCOS_SEMAPHORE_T complete_semaphore;

void encoder_buffer_callback(MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T *buffer)
{
  mmal_buffer_header_mem_lock(buffer);

    int len = buffer->length;
  char *pMem = (char *)buffer->data;
  cnt++;
    //memset(buffer->data,rand()%255,buffer->length/3);
   printf("encoder callback  cmd=0x%08x  cnt=%d len=%d\n", buffer->cmd,cnt,len);



   MMAL_STATUS_T status = MMAL_SUCCESS;
      MMAL_BUFFER_HEADER_T *new_buffer;

      new_buffer = mmal_queue_get(pool->queue);

      if (new_buffer)
      {
         status = mmal_port_send_buffer(port, new_buffer);
      }

     mmal_buffer_header_release(buffer);


     buffer->flags |= MAL_BUFFER_HEADER_FLAG_FRAME_END;

    mmal_buffer_header_mem_unlock(buffer);

    vcos_semaphore_post(&complete_semaphore);
}


void default_camera_control_callback(MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T *buffer)
{

  int len = buffer->length;
  char *pMem = (char *)buffer->data;
  cnt++;
    //memset(buffer->data,rand()%255,buffer->length/3);
   printf("control callback  cmd=0x%08x  cnt=%d len=%d\n", buffer->cmd,cnt,buffer->alloc_size);

   mmal_buffer_header_release(buffer);

}

int main()
{
    long usrdat;

    if ((status = mmal_component_create(MMAL_COMPONENT_DEFAULT_VIDEO_RENDERER, &preview)) != MMAL_SUCCESS)
        return status;

    if ((status = mmal_component_create(MMAL_COMPONENT_DEFAULT_CAMERA, &camera)) != MMAL_SUCCESS)
        return status;


    if ((status = mmal_component_create(MMAL_COMPONENT_DEFAULT_IMAGE_ENCODER, &encoder))!= MMAL_SUCCESS)
        return status;

    mmal_format_copy(encoder->output[0]->format, encoder->input[0]->format);


    if ((status = mmal_port_format_commit(camera->output[0])) != MMAL_SUCCESS)
        return status;

    vcos_status = vcos_semaphore_create(&complete_semaphore, "RaspiStill-sem", 0);


    pool = mmal_port_pool_create(encoder->output[0], encoder->output[0]->buffer_num, encoder->output[0]->buffer_size);

    // Set the JPEG quality level
    //status = mmal_port_parameter_set_uint32(encoder->output[0], MMAL_PARAMETER_JPEG_Q_FACTOR, 85);


    // Enable the encoder output port and tell it its callback function
     if ((status = mmal_port_enable(encoder->output[0], encoder_buffer_callback)) != MMAL_SUCCESS)
          return status;


     int num, q;
     // Send all the buffers to the encoder output port
     num = mmal_queue_length(pool->queue);

     for (q = 0; q < num; q++)
     {
         MMAL_BUFFER_HEADER_T* buffer = mmal_queue_get(pool->queue);

         if (!buffer)
             return status;

         if (mmal_port_send_buffer(encoder->output[0], buffer) != MMAL_SUCCESS)
             return status;
     }


     MMAL_PARAMETER_CHANGE_EVENT_REQUEST_T change_event_request =
         {{MMAL_PARAMETER_CHANGE_EVENT_REQUEST, sizeof(MMAL_PARAMETER_CHANGE_EVENT_REQUEST_T)},
          MMAL_PARAMETER_CAMERA_SETTINGS, 1};

     if ((status = mmal_port_parameter_set(camera->control, &change_event_request.hdr)) != MMAL_SUCCESS)
        return status;

    // Enable the camera, and tell it its control callback function
    if ((status = mmal_port_enable(camera->control, default_camera_control_callback)) != MMAL_SUCCESS)
        return status;


    if ((status = mmal_component_enable(camera)) != MMAL_SUCCESS)
        return status;


    //if (mmal_port_parameter_set_boolean(camera->output[0], MMAL_PARAMETER_ENABLE_RAW_CAPTURE, 1) != MMAL_SUCCESS)
      //  return status;


    MMAL_CONNECTION_T *encoder_connection;
    if ((status = mmal_connection_create(&encoder_connection, camera->output[0], encoder->input[0], MMAL_CONNECTION_FLAG_TUNNELLING | MMAL_CONNECTION_FLAG_ALLOCATION_ON_INPUT)) != MMAL_SUCCESS)
        return status;

    if ((status = mmal_connection_enable(encoder_connection)) != MMAL_SUCCESS)
         return status;

/*
    MMAL_CONNECTION_T *preview_connection;
    if ((status = mmal_connection_create(&preview_connection, camera->output[0], preview->input[0], MMAL_CONNECTION_FLAG_TUNNELLING | MMAL_CONNECTION_FLAG_ALLOCATION_ON_INPUT)) != MMAL_SUCCESS)
       return 0;

     if ((status = mmal_connection_enable(preview_connection)) != MMAL_SUCCESS)
       return 0;
*/

 //mmal_port_parameter_set_boolean(camera->output[0], MMAL_PARAMETER_CAPTURE, 1);

    sleep(10);

    vcos_semaphore_delete(&complete_semaphore);
    //mmal_connection_destroy(preview_connection);
    //mmal_component_destroy(encoder);
    //mmal_component_destroy(camera);
    //mmal_component_destroy(preview);

    return 0;
}

`

**Comment by 6by9** [comment] 2022-09-04 20:23
This is a closed issue, therefore please start a new one if you really have an issue.

Gut reaction is that your encoder_buffer_callback is wrong
```
void encoder_buffer_callback(MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T *buffer)
{
mmal_buffer_header_mem_lock(buffer);

int len = buffer->length;

char *pMem = (char *)buffer->data;
cnt++;
//memset(buffer->data,rand()%255,buffer->length/3);
printf("encoder callback cmd=0x%08x cnt=%d len=%d\n", buffer->cmd,cnt,len);

MMAL_STATUS_T status = MMAL_SUCCESS;
MMAL_BUFFER_HEADER_T *new_buffer;

  new_buffer = mmal_queue_get(pool->queue);
  if (new_buffer)
  {
     status = mmal_port_send_buffer(port, new_buffer);
  }
 mmal_buffer_header_release(buffer);

 buffer->flags |= MAL_BUFFER_HEADER_FLAG_FRAME_END;
mmal_buffer_header_mem_unlock(buffer);
vcos_semaphore_post(&complete_semaphore);
}
```
The default for the image encoder is for a single buffer, therefore ```mmal_queue_get``` won't find another buffer to send, and so it will die. due to there not being a buffer to fill.

Looking at ```buffer->flags``` after you've called ```mmal_buffer_header_release``` is also not valid, same as accessing memory allocated with malloc after having called free on it.

**Comment by KahnSoft** [comment] 2022-09-05 00:33
Thx for answer i will analyse it, atm this interface is not easy to handle.

**Comment by KahnSoft** [comment] 2022-09-18 22:46
Thank you after long jury of coding i have now encoder and camera , works . but the only possible format ist h264  this format is not streamable about html5.  Have anyone a Solution to generate mpeg files or anything to stream it directly into html5 tag , that all works with ogg or mp4 videos .
thx for any information
  Karsten
